###
GET http://localhost:3000

###
GET http://localhost:3000/projects
###
GET http://localhost:3000/journals
###
GET http://localhost:3000/journals/top5
###
GET http://localhost:3000/test

###
POST http://localhost:3000/project
Content-Type: application/json

{
    "title": "Encryption Program",
    "content": "I've been working on a program that can encrypt and decrypt a USB drive. This is the process"
}

###
POST http://localhost:3000/journal
Content-Type: application/json

{
    "project_id" : 2,
    "title": "USB- Encryption Attempt 1",
    "content": "After talking with Grok, a popular AI model, I determined that because I did not program in proper precautions to the flash drive, the USB was improperly reporting when it was done writing and reading. Particularly when it got to the big files this became a problem and cause some corruption. The new version included some os level protections for the drive."
}