CREATE TABLE projects (
  ID SERIAL PRIMARY KEY, 
  title VARCHAR(255) DEFAULT '[Redacted]',
  content TEXT NOT NULL,
  start_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end_date TIMESTAMP DEFAULT NULL
);

CREATE TABLE journals (
  ID SERIAL PRIMARY KEY, 
  CONSTRAINT project_id
    FOREIGN KEY (ID)
    REFERENCES projects(ID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  title VARCHAR(255) DEFAULT '[Redacted]',
  content TEXT NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
